In [1]:
import os
os.chdir('../')

In [2]:
import pandas as pd

# 1. Import data:

In [3]:
df = pd.read_csv('data/toronto-business-licenses-data.csv',encoding='utf-8')

/tmp/ipykernel_39210/3784590970.py:1: DtypeWarning: Columns (7,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/toronto-business-licenses-data.csv',encoding='utf-8')

# 2. Data Cleaning

In [4]:
df.head()

,_id,Category,Licence No.,Operating Name,Issued,Client Name,Business Phone,Business Phone Ext.,Licence Address Line 1,Licence Address Line 2,Licence Address Line 3,Ward,Conditions,Free Form Conditions Line 1,Free Form Conditions Line 2,Plate No.,Endorsements,Cancel Date,Last Record Update
0,1,PRIVATE TRANSPORTATION COMPANY,B02-4741962,TAXIFY,2018-01-18,TAXIFY CANADA INC,NaN,NaN,"35 OAK ST, #304","TORONTO, ON",M9N 1A1,5.0,TAXIFY;,NaN,NaN,NaN,PRIVATE TRANSPORTATION COMPANY;,2018-12-07,2018-12-07
1,2,PRIVATE TRANSPORTATION COMPANY,B02-4728645,INSTARYDE,2017-09-08,INSTARYDE INC,NaN,NaN,425 ALNESS ST,"TORONTO, ON",M3J 2T8,6.0,INSTARYDE;,NaN,NaN,NaN,PRIVATE TRANSPORTATION COMPANY;,2018-12-10,2019-05-06
2,3,PRIVATE TRANSPORTATION COMPANY,B02-4807677,DRIVEHER TRANSPORTATION,2018-03-08,DRIVEHER TRANSPORTATION INC,NaN,NaN,"100 DUNDAS ST E, #502","MISSISSAUGA, ON",L5A 1W5,NaN,DRIVEHER;,NaN,NaN,NaN,PRIVATE TRANSPORTATION COMPANY;,2021-12-23,2021-12-23
3,4,PRIVATE TRANSPORTATION COMPANY,B02-4714142,RIDEIN,2017-05-18,RIDE INC,NaN,NaN,379 BERING AVE,"TORONTO, ON",M8Z 3B1,3.0,RIDEIN;,NaN,NaN,NaN,PRIVATE TRANSPORTATION COMPANY;,2023-05-01,2023-06-07
4,5,PRIVATE TRANSPORTATION COMPANY,B02-5006733,CAPPTIN,2020-07-21,CAPPTIN TECHNOLOGIES (CND) INC,NaN,NaN,"4950 YONGE ST, #2200","TORONTO, ON",M2N 6K1,18.0,CAPPTIN;,NaN,NaN,NaN,PRIVATE TRANSPORTATION COMPANY;,2023-05-01,2023-06-07

## 2.1. lowercase column names

In [5]:
df.columns

Index(['_id', 'Category', 'Licence No.', 'Operating Name', 'Issued',
       'Client Name', 'Business Phone', 'Business Phone Ext.',
       'Licence Address Line 1', 'Licence Address Line 2',
       'Licence Address Line 3', 'Ward', 'Conditions',
       'Free Form Conditions Line 1', 'Free Form Conditions Line 2',
       'Plate No.', 'Endorsements', 'Cancel Date', 'Last Record Update'],
      dtype='object')

In [6]:
df.columns = [c.lower() for c in df.columns]

## 2.2. Set correct dtypes
1. datetime: `Issued`, `Cancel Date`, `Last Record Update`
2. Category: `category`, `ward`

### 2.2.1. datetime

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160099 entries, 0 to 160098
Data columns (total 19 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   _id                          160099 non-null  int64
 1   category                     160099 non-null  object
 2   licence no.                  160099 non-null  object
 3   operating name               130619 non-null  object
 4   issued                       160099 non-null  object
 5   client name                  160099 non-null  object
 6   business phone               15245 non-null   float64
 7   business phone ext.          1083 non-null    object
 8   licence address line 1       134656 non-null  object
 9   licence address line 2       134656 non-null  object
 10  licence address line 3       159360 non-null  object
 11  ward                         137654 non-null  float64
 12  conditions                   80010 non-null   object
 13  free form conditions line 1  44664 non-null   object
 14  free form conditions line 2  12316 non-null   object
 15  plate no.                    22855 non-null   object
 16  endorsements                 160099 non-null  object
 17  cancel date                  123406 non-null  object
 18  last record update           160099 non-null  object
dtypes: float64(2), int64(1), object(16)
memory usage: 23.2+ MB

In [8]:
date_cols = ['issued', 'cancel date', 'last record update']
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors = 'coerce')

### 2.2.2. Category

In [14]:
df[['category', 'ward']] = df[['category', 'ward']].astype('category')

In [9]:
df.head()

,_id,category,licence no.,operating name,issued,client name,business phone,business phone ext.,licence address line 1,licence address line 2,licence address line 3,ward,conditions,free form conditions line 1,free form conditions line 2,plate no.,endorsements,cancel date,last record update
0,1,PRIVATE TRANSPORTATION COMPANY,B02-4741962,TAXIFY,2018-01-18,TAXIFY CANADA INC,NaN,NaN,"35 OAK ST, #304","TORONTO, ON",M9N 1A1,5.0,TAXIFY;,NaN,NaN,NaN,PRIVATE TRANSPORTATION COMPANY;,2018-12-07,2018-12-07
1,2,PRIVATE TRANSPORTATION COMPANY,B02-4728645,INSTARYDE,2017-09-08,INSTARYDE INC,NaN,NaN,425 ALNESS ST,"TORONTO, ON",M3J 2T8,6.0,INSTARYDE;,NaN,NaN,NaN,PRIVATE TRANSPORTATION COMPANY;,2018-12-10,2019-05-06
2,3,PRIVATE TRANSPORTATION COMPANY,B02-4807677,DRIVEHER TRANSPORTATION,2018-03-08,DRIVEHER TRANSPORTATION INC,NaN,NaN,"100 DUNDAS ST E, #502","MISSISSAUGA, ON",L5A 1W5,NaN,DRIVEHER;,NaN,NaN,NaN,PRIVATE TRANSPORTATION COMPANY;,2021-12-23,2021-12-23
3,4,PRIVATE TRANSPORTATION COMPANY,B02-4714142,RIDEIN,2017-05-18,RIDE INC,NaN,NaN,379 BERING AVE,"TORONTO, ON",M8Z 3B1,3.0,RIDEIN;,NaN,NaN,NaN,PRIVATE TRANSPORTATION COMPANY;,2023-05-01,2023-06-07
4,5,PRIVATE TRANSPORTATION COMPANY,B02-5006733,CAPPTIN,2020-07-21,CAPPTIN TECHNOLOGIES (CND) INC,NaN,NaN,"4950 YONGE ST, #2200","TORONTO, ON",M2N 6K1,18.0,CAPPTIN;,NaN,NaN,NaN,PRIVATE TRANSPORTATION COMPANY;,2023-05-01,2023-06-07

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160099 entries, 0 to 160098
Data columns (total 19 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   _id                          160099 non-null  int64
 1   category                     160099 non-null  object
 2   licence no.                  160099 non-null  object
 3   operating name               130619 non-null  object
 4   issued                       160099 non-null  datetime64[ns]
 5   client name                  160099 non-null  object
 6   business phone               15245 non-null   float64
 7   business phone ext.          1083 non-null    object
 8   licence address line 1       134656 non-null  object
 9   licence address line 2       134656 non-null  object
 10  licence address line 3       159360 non-null  object
 11  ward                         137654 non-null  float64
 12  conditions                   80010 non-null   object
 13  free form conditions line 1  44664 non-null   object
 14  free form conditions line 2  12316 non-null   object
 15  plate no.                    22855 non-null   object
 16  endorsements                 160099 non-null  object
 17  cancel date                  123406 non-null  datetime64[ns]
 18  last record update           160099 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(1), object(13)
memory usage: 23.2+ MB